version: '3.9'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  server:
    depends_on:
      - redis
    build: ./
    restart: on-failure
    ports:
      - '80:3000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /app/node_modules
    environment:
      - REDIS_HOST=redis
